### ISSUE TITLE
Signifier

### ISSUE THREAD

**Issue by ghost** [Seb85/Avatar-Plugin-Parle#1]
Bonjour seb85,
Tu peux nous expliquer a quois sert le plugin parle
cordialemrnt

**Comment by Seb85** [comment]
Bonjour Halimgambit,
J'utilisais toujours sur jeedom le plugin sarah pour le TTS. Le souci était qu'Avatar s’entendait en même temps lors d'une écoute..
Ce plugin permet de pallier a ça. Je l’exécute avec une requête http avec le texte :
http://192.168.1.2:3000/Avatar/parle?command=parle&txt=Salut&client=Salon
